{
 "title": "K6 Unified Storage",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "testid",
    "label": "Test ID",
    "query": {
     "query": "label_values(k6_iterations_total,testid)"
    }
   }
  ]
 },
 "panels": [
  { "title": "gRPC Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "gRPC Request Latencies",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(method, le) (k6_grpc_req_duration_seconds{testid=\"$testid\",method!=\"List\",url!=\"\"})) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total GRPC Requests (Successful)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method) (k6_grpc_requests_total{testid=\"$testid\", status=\"OK\"})",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "GRPC req/sec (Successful)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method) (rate(k6_grpc_requests_total{testid=\"$testid\", status=\"OK\"}[30s]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "GRPC Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (method, status, respstatus) (\n    rate(k6_grpc_requests_total{status!=\"OK\"}[$__rate_interval])\n)\n/\nignoring (status,respstatus) group_left \nsum by (method) (\n    rate(k6_grpc_requests_total[$__rate_interval])\n) * 100",
     "legendFormat": "{{method}} - {{status}}:{{respstatus}}"
    }
   ]
  },
  { "title": "Watch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Watch Events Received",
   "type": "timeseries",
   "description": "The rate of watch events received over time, grouped by action. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum by(action) (rate(k6_watch_events_recieved_total{testid=\"$testid\"}[30s]))",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Watch Latency",
   "type": "heatmap",
   "description": "The latency between the event being dispatched and it being received by a client.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, k6_watch_event_latency{testid=~\"$testid\"})",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Watch Events Received Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (action) (k6_watch_events_recieved_total{testid=\"$testid\"})",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Watch Events Received: Mean",
   "type": "stat",
   "description": "The rate of watch events received over time, grouped by action. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(action) (rate(k6_watch_events_recieved_total{testid=~\"$testid\"}[30s]))",
     "legendFormat": "{{action}}"
    }
   ]
  },
  { "title": "List", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Total Entities Listed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k6_list_entities_total{testid=\"$testid\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}