{
 "title": "K6 Unified Storage",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "testid",
    "label": "Test ID",
    "query": {
     "query": "label_values(k6_iterations_total,testid)"
    }
   }
  ]
 },
 "panels": [
  { "title": "gRPC Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "gRPC Request Latencies",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(method, le) (rate(k6_grpc_req_duration_seconds{testid=\"$testid\"}[$__rate_interval]))) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Watch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Watch Events Received",
   "type": "timeseries",
   "description": "The rate of watch events received over time, grouped by action. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum by(action) (rate(k6_watch_events_recieved_total{testid=\"$testid\"}[$__rate_interval]))",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Watch Latency",
   "type": "heatmap",
   "description": "The latency between the event being dispatched and it being received by a client.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(k6_watch_event_latency{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Watch Events Received Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k6_watch_events_recieved_total{testid=\"$testid\"}",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Watch Events Received: Mean",
   "type": "stat",
   "description": "The rate of watch events received over time, grouped by action. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(action) (rate(k6_watch_events_recieved_total{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "{{action}}"
    }
   ]
  }
 ]
}